# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from democrai.core.infrastructure.ai.engine.invocation.proto import engine_orchestrator_pb2 as engine__orchestrator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/Status',
                request_serializer=engine__orchestrator__pb2.EngineStatusRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.EngineStatusResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/Invoke',
                request_serializer=engine__orchestrator__pb2.EngineInvokeRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.EngineInvokeResponse.FromString,
                _registered_method=True)
        self.InvokeStream = channel.unary_stream(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/InvokeStream',
                request_serializer=engine__orchestrator__pb2.EngineInvokeRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.EngineStreamChunk.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/Cancel',
                request_serializer=engine__orchestrator__pb2.EngineCancelRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.EngineCancelResponse.FromString,
                _registered_method=True)
        self.RefreshRegistries = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/RefreshRegistries',
                request_serializer=engine__orchestrator__pb2.RefreshRegistriesRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.RefreshRegistriesResponse.FromString,
                _registered_method=True)
        self.SyncActiveEngines = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/SyncActiveEngines',
                request_serializer=engine__orchestrator__pb2.SyncActiveEnginesRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.SyncActiveEnginesResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/UnloadModel',
                request_serializer=engine__orchestrator__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.StopEngine = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/StopEngine',
                request_serializer=engine__orchestrator__pb2.StopEngineRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.StopEngineResponse.FromString,
                _registered_method=True)
        self.InvokeEngineAction = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/InvokeEngineAction',
                request_serializer=engine__orchestrator__pb2.EngineActionRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.EngineInvokeResponse.FromString,
                _registered_method=True)
        self.InvokeEngineRuntime = channel.unary_unary(
                '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/InvokeEngineRuntime',
                request_serializer=engine__orchestrator__pb2.EngineRuntimeInvokeRequest.SerializeToString,
                response_deserializer=engine__orchestrator__pb2.EngineInvokeResponse.FromString,
                _registered_method=True)


class EngineOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshRegistries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncActiveEngines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeEngineAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeEngineRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=engine__orchestrator__pb2.EngineStatusRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.EngineStatusResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=engine__orchestrator__pb2.EngineInvokeRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.EngineInvokeResponse.SerializeToString,
            ),
            'InvokeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InvokeStream,
                    request_deserializer=engine__orchestrator__pb2.EngineInvokeRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.EngineStreamChunk.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=engine__orchestrator__pb2.EngineCancelRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.EngineCancelResponse.SerializeToString,
            ),
            'RefreshRegistries': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshRegistries,
                    request_deserializer=engine__orchestrator__pb2.RefreshRegistriesRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.RefreshRegistriesResponse.SerializeToString,
            ),
            'SyncActiveEngines': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncActiveEngines,
                    request_deserializer=engine__orchestrator__pb2.SyncActiveEnginesRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.SyncActiveEnginesResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=engine__orchestrator__pb2.UnloadModelRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.UnloadModelResponse.SerializeToString,
            ),
            'StopEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.StopEngine,
                    request_deserializer=engine__orchestrator__pb2.StopEngineRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.StopEngineResponse.SerializeToString,
            ),
            'InvokeEngineAction': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeEngineAction,
                    request_deserializer=engine__orchestrator__pb2.EngineActionRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.EngineInvokeResponse.SerializeToString,
            ),
            'InvokeEngineRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeEngineRuntime,
                    request_deserializer=engine__orchestrator__pb2.EngineRuntimeInvokeRequest.FromString,
                    response_serializer=engine__orchestrator__pb2.EngineInvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'democrai.ai.engine.orchestrator.v1.EngineOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('democrai.ai.engine.orchestrator.v1.EngineOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/Status',
            engine__orchestrator__pb2.EngineStatusRequest.SerializeToString,
            engine__orchestrator__pb2.EngineStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/Invoke',
            engine__orchestrator__pb2.EngineInvokeRequest.SerializeToString,
            engine__orchestrator__pb2.EngineInvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/InvokeStream',
            engine__orchestrator__pb2.EngineInvokeRequest.SerializeToString,
            engine__orchestrator__pb2.EngineStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/Cancel',
            engine__orchestrator__pb2.EngineCancelRequest.SerializeToString,
            engine__orchestrator__pb2.EngineCancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshRegistries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/RefreshRegistries',
            engine__orchestrator__pb2.RefreshRegistriesRequest.SerializeToString,
            engine__orchestrator__pb2.RefreshRegistriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncActiveEngines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/SyncActiveEngines',
            engine__orchestrator__pb2.SyncActiveEnginesRequest.SerializeToString,
            engine__orchestrator__pb2.SyncActiveEnginesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/UnloadModel',
            engine__orchestrator__pb2.UnloadModelRequest.SerializeToString,
            engine__orchestrator__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/StopEngine',
            engine__orchestrator__pb2.StopEngineRequest.SerializeToString,
            engine__orchestrator__pb2.StopEngineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeEngineAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/InvokeEngineAction',
            engine__orchestrator__pb2.EngineActionRequest.SerializeToString,
            engine__orchestrator__pb2.EngineInvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeEngineRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.ai.engine.orchestrator.v1.EngineOrchestrator/InvokeEngineRuntime',
            engine__orchestrator__pb2.EngineRuntimeInvokeRequest.SerializeToString,
            engine__orchestrator__pb2.EngineInvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
