# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from democrai.core.application.knowledge.query.proto import knowledge_query_pb2 as knowledge__query__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeQueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/democrai.knowledge.query.v1.KnowledgeQuery/Status',
                request_serializer=knowledge__query__pb2.KnowledgeQueryStatusRequest.SerializeToString,
                response_deserializer=knowledge__query__pb2.KnowledgeQueryStatusResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/democrai.knowledge.query.v1.KnowledgeQuery/Retrieve',
                request_serializer=knowledge__query__pb2.KnowledgeRetrieveRequest.SerializeToString,
                response_deserializer=knowledge__query__pb2.KnowledgeRetrieveResponse.FromString,
                _registered_method=True)


class KnowledgeQueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=knowledge__query__pb2.KnowledgeQueryStatusRequest.FromString,
                    response_serializer=knowledge__query__pb2.KnowledgeQueryStatusResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=knowledge__query__pb2.KnowledgeRetrieveRequest.FromString,
                    response_serializer=knowledge__query__pb2.KnowledgeRetrieveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'democrai.knowledge.query.v1.KnowledgeQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('democrai.knowledge.query.v1.KnowledgeQuery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeQuery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.knowledge.query.v1.KnowledgeQuery/Status',
            knowledge__query__pb2.KnowledgeQueryStatusRequest.SerializeToString,
            knowledge__query__pb2.KnowledgeQueryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.knowledge.query.v1.KnowledgeQuery/Retrieve',
            knowledge__query__pb2.KnowledgeRetrieveRequest.SerializeToString,
            knowledge__query__pb2.KnowledgeRetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
