# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: knowledge_query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'knowledge_query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15knowledge_query.proto\x12\x1b\x64\x65mocrai.knowledge.query.v1\"\x1d\n\x1bKnowledgeQueryStatusRequest\"p\n\x1cKnowledgeQueryStatusResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x12\n\nstarted_at\x18\x04 \x01(\t\x12\x12\n\nconfigured\x18\x05 \x01(\x08\"\xdf\x01\n\x18KnowledgeRetrieveRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nquery_text\x18\x02 \x01(\t\x12\x19\n\x11query_vector_json\x18\x03 \x01(\t\x12\r\n\x05top_k\x18\x04 \x01(\x05\x12\x15\n\rlexical_limit\x18\x05 \x01(\x05\x12\x1d\n\x15graph_neighbors_limit\x18\x06 \x01(\x05\x12\x1d\n\x15metadata_filters_json\x18\x07 \x01(\t\x12\x1c\n\x14request_context_json\x18\x08 \x01(\t\"^\n\x19KnowledgeRetrieveResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x11\n\ttraceback\x18\x04 \x01(\t2\x8a\x02\n\x0eKnowledgeQuery\x12}\n\x06Status\x12\x38.democrai.knowledge.query.v1.KnowledgeQueryStatusRequest\x1a\x39.democrai.knowledge.query.v1.KnowledgeQueryStatusResponse\x12y\n\x08Retrieve\x12\x35.democrai.knowledge.query.v1.KnowledgeRetrieveRequest\x1a\x36.democrai.knowledge.query.v1.KnowledgeRetrieveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'knowledge_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KNOWLEDGEQUERYSTATUSREQUEST']._serialized_start=54
  _globals['_KNOWLEDGEQUERYSTATUSREQUEST']._serialized_end=83
  _globals['_KNOWLEDGEQUERYSTATUSRESPONSE']._serialized_start=85
  _globals['_KNOWLEDGEQUERYSTATUSRESPONSE']._serialized_end=197
  _globals['_KNOWLEDGERETRIEVEREQUEST']._serialized_start=200
  _globals['_KNOWLEDGERETRIEVEREQUEST']._serialized_end=423
  _globals['_KNOWLEDGERETRIEVERESPONSE']._serialized_start=425
  _globals['_KNOWLEDGERETRIEVERESPONSE']._serialized_end=519
  _globals['_KNOWLEDGEQUERY']._serialized_start=522
  _globals['_KNOWLEDGEQUERY']._serialized_end=788
# @@protoc_insertion_point(module_scope)
