# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime_prompt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'runtime_prompt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14runtime_prompt.proto\x12\x1a\x64\x65mocrai.runtime_prompt.v1\"\xac\x02\n\x14RuntimePromptRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63tions_json\x18\x03 \x01(\t\x12\x15\n\rrequired_role\x18\x04 \x01(\t\x12\x1d\n\x15required_access_level\x18\x05 \x01(\x05\x12!\n\x19required_permissions_json\x18\x06 \x01(\t\x12\x1c\n\x14request_context_json\x18\x07 \x01(\t\x12\x15\n\rmetadata_json\x18\x08 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\t \x01(\x01\x12\x17\n\x0f\x66orm_model_json\x18\n \x01(\t\x12\x18\n\x10\x66orm_values_json\x18\x0b \x01(\t\"\x7f\n\x15RuntimePromptResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x11\n\tprompt_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x15\n\rmetadata_json\x18\x05 \x01(\t\x12\x11\n\tdata_json\x18\x06 \x01(\t2\x88\x01\n\rRuntimePrompt\x12w\n\x10\x41skRuntimePrompt\x12\x30.democrai.runtime_prompt.v1.RuntimePromptRequest\x1a\x31.democrai.runtime_prompt.v1.RuntimePromptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime_prompt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNTIMEPROMPTREQUEST']._serialized_start=53
  _globals['_RUNTIMEPROMPTREQUEST']._serialized_end=353
  _globals['_RUNTIMEPROMPTRESPONSE']._serialized_start=355
  _globals['_RUNTIMEPROMPTRESPONSE']._serialized_end=482
  _globals['_RUNTIMEPROMPT']._serialized_start=485
  _globals['_RUNTIMEPROMPT']._serialized_end=621
# @@protoc_insertion_point(module_scope)
