# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from democrai.core.application.runtime_prompt.grpc.proto import runtime_prompt_pb2 as runtime__prompt__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_prompt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimePromptStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskRuntimePrompt = channel.unary_unary(
                '/democrai.runtime_prompt.v1.RuntimePrompt/AskRuntimePrompt',
                request_serializer=runtime__prompt__pb2.RuntimePromptRequest.SerializeToString,
                response_deserializer=runtime__prompt__pb2.RuntimePromptResponse.FromString,
                _registered_method=True)


class RuntimePromptServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskRuntimePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimePromptServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskRuntimePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.AskRuntimePrompt,
                    request_deserializer=runtime__prompt__pb2.RuntimePromptRequest.FromString,
                    response_serializer=runtime__prompt__pb2.RuntimePromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'democrai.runtime_prompt.v1.RuntimePrompt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('democrai.runtime_prompt.v1.RuntimePrompt', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimePrompt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskRuntimePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/democrai.runtime_prompt.v1.RuntimePrompt/AskRuntimePrompt',
            runtime__prompt__pb2.RuntimePromptRequest.SerializeToString,
            runtime__prompt__pb2.RuntimePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
