"""A generic, single database configuration."""

# revision identifiers, used by Alembic.
revision = '93a0c99013fe'
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p_chat_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('extraction_request_id', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('p_chat_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_p_chat_attachment_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_attachment_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_attachment_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_attachment_user_id'), ['user_id'], unique=False)

    op.create_table('p_chat_chat_component',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('component_kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('p_chat_chat_component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_p_chat_chat_component_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_chat_component_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_chat_component_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_chat_component_sequence'), ['sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_chat_component_user_id'), ['user_id'], unique=False)

    op.create_table('p_chat_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_until_sequence', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('p_chat_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_p_chat_conversation_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_conversation_user_id'), ['user_id'], unique=False)

    op.create_table('p_chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('p_chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_p_chat_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_message_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_message_sequence'), ['sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_p_chat_message_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('p_chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_p_chat_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_message_sequence'))
        batch_op.drop_index(batch_op.f('ix_p_chat_message_organization_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_message_conversation_id'))

    op.drop_table('p_chat_message')
    with op.batch_alter_table('p_chat_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_p_chat_conversation_user_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_conversation_organization_id'))

    op.drop_table('p_chat_conversation')
    with op.batch_alter_table('p_chat_chat_component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_p_chat_chat_component_user_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_chat_component_sequence'))
        batch_op.drop_index(batch_op.f('ix_p_chat_chat_component_organization_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_chat_component_message_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_chat_component_conversation_id'))

    op.drop_table('p_chat_chat_component')
    with op.batch_alter_table('p_chat_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_p_chat_attachment_user_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_attachment_organization_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_attachment_message_id'))
        batch_op.drop_index(batch_op.f('ix_p_chat_attachment_conversation_id'))

    op.drop_table('p_chat_attachment')
    # ### end Alembic commands ###
