"""A generic, single database configuration."""

# revision identifiers, used by Alembic.
revision = "c1e98e4ef305"
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vector_indices",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("app_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "app_id", "name"),
    )
    op.create_table(
        "vector_payloads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("app_id", sa.String(), nullable=False),
        sa.Column("index_name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.Column("metadata", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "tenant_id", "app_id", "index_name", "user_id", "organization_id"
        ),
    )
    with op.batch_alter_table("vector_payloads", schema=None) as batch_op:
        batch_op.create_index(
            "idx_vector_payloads_scope",
            ["tenant_id", "app_id", "index_name", "user_id", "organization_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vector_payloads", schema=None) as batch_op:
        batch_op.drop_index("idx_vector_payloads_scope")

    op.drop_table("vector_payloads")
    op.drop_table("vector_indices")
    # ### end Alembic commands ###
