from __future__ import annotations

from typing import Any, Optional, Protocol


class JsonStoreProvider(Protocol):
    def load(self, key: str) -> Optional[dict[str, Any]]: ...
    def save(self, key: str, value: dict[str, Any]) -> None: ...
    def delete(self, key: str) -> None: ...
    def keys(self) -> list[str]: ...
