from __future__ import annotations

from democrai.core.infrastructure.sandbox.platform_policy import (
    LINUX_RUNTIME_DEPENDENCY_READ_PATHS,
    LINUX_SYSTEM_PROBE_READ_PATHS,
    DARWIN_RUNTIME_DEPENDENCY_READ_PATHS,
    DARWIN_SYSTEM_PROBE_READ_PATHS,
    WINDOWS_RUNTIME_DEPENDENCY_READ_FALLBACKS,
    WINDOWS_SYSTEM_PROBE_READ_FALLBACKS,
    platform_system_read_paths,
)


LINUX_SYSTEM_READ_PATHS = (
    *LINUX_SYSTEM_PROBE_READ_PATHS,
    *LINUX_RUNTIME_DEPENDENCY_READ_PATHS,
)
DARWIN_SYSTEM_READ_PATHS = (
    *DARWIN_SYSTEM_PROBE_READ_PATHS,
    *DARWIN_RUNTIME_DEPENDENCY_READ_PATHS,
)
WINDOWS_SYSTEM_READ_PATHS = (
    *WINDOWS_SYSTEM_PROBE_READ_FALLBACKS,
    *WINDOWS_RUNTIME_DEPENDENCY_READ_FALLBACKS,
)


def system_read_paths() -> tuple[str, ...]:
    return platform_system_read_paths()
