"""task_key

Revision ID: 363272cf7eb6
Revises: 8a31e4d5205c
Create Date: 2026-03-29 17:28:40.817027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363272cf7eb6'
down_revision: Union[str, Sequence[str], None] = '8a31e4d5205c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_key', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_background_tasks_task_key'), ['task_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_task_key'))
        batch_op.drop_column('task_key')

    # ### end Alembic commands ###
