"""update_module_lock

Revision ID: 692f51038ec1
Revises: dff03aa70222
Create Date: 2026-03-27 11:57:40.043453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692f51038ec1'
down_revision: Union[str, Sequence[str], None] = 'dff03aa70222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_lock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_module_lock_organization_id'))
        batch_op.drop_index(batch_op.f('ix_module_lock_user_id'))
        batch_op.create_foreign_key(
            'fk_module_lock_user_id_users', 'users', ['user_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_module_lock_role_id_roles', 'roles', ['role_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_module_lock_organization_id_organizations',
            'organizations',
            ['organization_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_lock', schema=None) as batch_op:
        batch_op.drop_constraint('fk_module_lock_organization_id_organizations', type_='foreignkey')
        batch_op.drop_constraint('fk_module_lock_role_id_roles', type_='foreignkey')
        batch_op.drop_constraint('fk_module_lock_user_id_users', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_module_lock_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_lock_organization_id'), ['organization_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
