"""AI engine management

Revision ID: 8a31e4d5205c
Revises: 692f51038ec1
Create Date: 2026-03-28 16:51:56.224678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a31e4d5205c"
down_revision: Union[str, Sequence[str], None] = "692f51038ec1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engine_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("supported", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("model_registry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("engine_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_engine_model", "engine_registry", ["engine_id"], ["id"]
        )
        batch_op.drop_column("provider")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_registry", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("provider", sa.VARCHAR(length=100), nullable=False)
        )
        batch_op.drop_constraint("fk_engine_model", type_="foreignkey")
        batch_op.drop_column("engine_id")

    op.drop_table("engine_registry")
    # ### end Alembic commands ###
