"""Add model registry and objective mappings

Revision ID: 9110114990f1
Revises: b78cb708cc2c
Create Date: 2026-02-07 12:45:21.617696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9110114990f1"
down_revision: Union[str, Sequence[str], None] = "b78cb708cc2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model_path", sa.String(length=512), nullable=True),
        sa.Column("vram_required_mb", sa.Integer(), nullable=True),
        sa.Column("ram_required_mb", sa.Integer(), nullable=True),
        sa.Column("is_downloaded", sa.Integer(), nullable=True),
        sa.Column("remote_url", sa.String(length=512), nullable=True),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("capabilities", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "objective_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("objective", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_registry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("objective"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("objective_mappings")
    op.drop_table("model_registry")
    # ### end Alembic commands ###
