"""Add language to User

Revision ID: d97fd2fdedb3
Revises: c89de819ff3g
Create Date: 2026-02-17 10:24:09.263647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d97fd2fdedb3"
down_revision: Union[str, Sequence[str], None] = "c89de819ff3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_key"), table_name="sessions")
    op.create_index(op.f("ix_sessions_user_key"), "sessions", ["user_key"], unique=True)
    op.add_column("users", sa.Column("language", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language")
    op.drop_index(op.f("ix_sessions_user_key"), table_name="sessions")
    op.create_index(
        op.f("ix_sessions_user_key"), "sessions", ["user_key"], unique=False
    )
    # ### end Alembic commands ###
