"""create_module_lock

Revision ID: dff03aa70222
Revises: c1d2e3f4a5b6
Create Date: 2026-03-27 11:49:31.226611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff03aa70222'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_lock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_lock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_lock_module_name'), ['module_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_lock_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_lock_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('external_access_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_access_approvals_approval_key'))
        batch_op.create_index(batch_op.f('ix_external_access_approvals_approval_key'), ['approval_key'], unique=True)

    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sources_status'), ['status'], unique=False)

    with op.batch_alter_table('media_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_uploads_file_id'))
        batch_op.create_index(batch_op.f('ix_media_uploads_file_id'), ['file_id'], unique=True)

    with op.batch_alter_table('session_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_identities_session_key'))
        batch_op.create_index(batch_op.f('ix_session_identities_session_key'), ['session_key'], unique=True)

    with op.batch_alter_table('session_ui_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_ui_states_session_key'))
        batch_op.create_index(batch_op.f('ix_session_ui_states_session_key'), ['session_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_ui_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_ui_states_session_key'))
        batch_op.create_index(batch_op.f('ix_session_ui_states_session_key'), ['session_key'], unique=False)

    with op.batch_alter_table('session_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_identities_session_key'))
        batch_op.create_index(batch_op.f('ix_session_identities_session_key'), ['session_key'], unique=False)

    with op.batch_alter_table('media_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_uploads_file_id'))
        batch_op.create_index(batch_op.f('ix_media_uploads_file_id'), ['file_id'], unique=False)

    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_status'))

    with op.batch_alter_table('external_access_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_access_approvals_approval_key'))
        batch_op.create_index(batch_op.f('ix_external_access_approvals_approval_key'), ['approval_key'], unique=False)

    with op.batch_alter_table('module_lock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_lock_user_id'))
        batch_op.drop_index(batch_op.f('ix_module_lock_organization_id'))
        batch_op.drop_index(batch_op.f('ix_module_lock_module_name'))

    op.drop_table('module_lock')
    # ### end Alembic commands ###
