"""initial_observability_schema

Revision ID: 07f885fd6398
Revises:
Create Date: 2026-02-07 12:20:13.715195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "07f885fd6398"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=True),
        sa.Column("event_name", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("idx_events_category", ["category"], unique=False)
        batch_op.create_index(
            "idx_events_composite", ["user_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_events_correlation", ["correlation_id"], unique=False
        )
        batch_op.create_index("idx_events_ts", ["timestamp"], unique=False)
        batch_op.create_index("idx_events_user", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("idx_events_user")
        batch_op.drop_index("idx_events_ts")
        batch_op.drop_index("idx_events_correlation")
        batch_op.drop_index("idx_events_composite")
        batch_op.drop_index("idx_events_category")

    op.drop_table("events")
    # ### end Alembic commands ###
